name: SSBC Members

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * MON'

jobs:
  members:
    runs-on: ubuntu-latest

    steps:
      - uses: staltz/trustnet-org@v1.2.0
        with:
          token: ${{ secrets.SSBC_MEMBERS }}
          org: ssbc
          pioneer: dominictarr
          trustThreshold: 4
          minMemberCount: 3
          inactiveAfter: 12 # months
          blocklist: |
            dependabot[bot]
          ignoreRepos: |
            .github
            ssbc-org
            level-sublevel
            forked-systray
            open-dyslexic
            electron-spellchecker-prebuilt
            paulcbetts-spellchecker-prebuilt
            keyboard-layout-prebuilt
            grants-process
            opencollective_page
            somebodyshould
            ssbc-rituals
            scuttlebutt-guide
            village-tracker
            scuttlebutt-technology
            ssbc.github.io
            docs
