name: SSBC Members

on: workflow_dispatch

jobs:
  members:
    runs-on: ubuntu-latest

    steps:
      - uses: staltz/gha-sandbox@main
        with:
          token: ${{ secrets.SSBC_MEMBERS }}
          org: ssbc
