name: Mirror NPM

on:
  workflow_dispatch:
    inputs:
      owners:
        description: 'NPM accounts to give publish permissions, separated by commas'
        required: true
        type: string

jobs:
  mirror-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./actions/mirror-npm/action.yml
        with:
          token: ${{ secrets.SSBC_MEMBERS }}
          org: ${{ github.repository_owner }}
          owners: ${{ github.event.inputs.owners }}